tasks:
  - import_data_from_ftp:
      class: SomeClass
      arguments:
        - name: arg1
          type: bool
          value: True
        - name: arg2
          type: list
          value: [1,2,3]
        - name: arg3
          type: int
          value: 4
        - name: arg4
          type: float
          value: 3.4
        - name: arg5
          type: str
          value: hello World
  